name: GOAT Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Preparar codigo"
        uses: actions/checkout@v4

      - name: "Instalar Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Instalar Horusec"
        run: |
          sudo apt-get -y install jq
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta

      - name: "Ejecutar SAST"
        run: horusec start -p="./"

      - name: "Compilacion del codigo"
        run: ./mvnw clean install

      - name: "Evaluacion SCA"
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: DepCheck
        with:
          project: 'GOAT'
          path: '.'
          format: 'XML'
          out: 'reports'
          args: >
            --disableRetireJS

      - name: "Crear imagen Docker"
        run: |
          docker build -f Dockerfile . -t webgoat/test
          docker images