name: GOAT Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Preparar codigo"
        uses: actions/checkout@v4

      - name: "Instalar Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilacion del codigo"
        run: ./mvnw clean install

      - name: "Evaluacion SCA"
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: DepCheck
        with:
          project: 'GOAT'
          path: '.'
          format: 'XML'
          out: 'reports'
          args: >
            --disableRetireJS

      - name: "Crear imagen Docker"
        run: |
          docker build -f Dockerfile . -t webgoat/test
          docker images

      - name: "Evaluacion Docker Image - Image Scanning"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'webgoat/test'
          format: 'json'
          output: 'trivy-resultados.json'
          timeout: 10m0s
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          scanners: vuln,secret,config